triggerCheckerPeriod: 10
scriptCheckerPeriod: 100
startUpDelay: 200
drive:
  accessToken: xxx
  refreshToken: xxx
  animationsFolder: google drive folder ID
  entitiesFolder: google drive folder ID
  scriptsFolder: google drive folder ID
  clientId: google app client ID
  clientSecret: google app client secret

# careful with wildcard '*'! There should be a SPACE after command, otherwise similar commands with same start will all be whitelisted too.
commandWhitelist:
  - "say *"
  - "gamemode survival"